### PR TITLE
Coverage repair - Closes #585

### LINKED ISSUE #585: Repair coveralls reports
### Description

Coveralls does not respond on reports

### Steps to Reproduce

1. Create a PR
1. Submit the PR, let Jenkins run
1. Coveralls does not respond with a report

**Expected behavior:**

Coveralls should report the amount of coverage

**Actual behavior:** 

Coveralls does not respond with a coverage

**Version**

1.0.0

### PR DESCRIPTION
**Pull request by toschdev**
Closes #585

### CODE REVIEW

**Comment by willclarktech** [comment]
Do we need to update lisk-template with these changes?

**Comment by karmacoma** [comment]
What exactly are we fixing in coveralls here?

**Comment by willclarktech** [comment]
@karmacoma Coveralls stopped reporting to GitHub.

**Comment by Tosch110** [comment]
Seems to be an issue with coveralls.io. It started reporting again.

**Pull request closed without merging**
