### PR TITLE
Remove redundant keys in package.json - Closes #639

### LINKED ISSUE #639: Remove redundant scripts from package.json
**Expected behavior:** There should be no redundant scripts in package.json

**Actual behavior:** We have a few duplicate keys, probably as a result of rebasing at some point.

### Versions

1.0.0

### PR DESCRIPTION
**Pull request by webmaster128**
### What was the problem?

There are redundant keys in `scripts` dictionary of package.json

### How did I fix it?

This should not happen

### How to test it?

See file

### Review checklist

* The PR solves #639 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Review by willclarktech — APPROVED** [review]

**Comment by willclarktech** [comment]
Thanks @webmaster128! In future, we prefer it if contributors create an issue before submitting a PR: it helps keep it clear why changes have been made.

**Comment by webmaster128** [comment]
@willclarktech Thanks for the feedback

> In future, we prefer it if contributors create an issue before submitting a PR: it helps keep it clear why changes have been made.

Could you explain to me why this makes sense for Lisk? I never came across this workflow in any other open source project I contributed to or in any of the companies I worked in.

Especially for small cleanup fixes it is a massive overhead:

Issue

* Title: Code has bug X
* Expected behaviour: code should not be buggy
* Actual behaviour: code has bug X

PR

* Title: Fix bug X
* Commit message: Fix bug X and explain why
* What was the problem?: Code has bug X
* How did I fix it?: Fix bug X in code

I agree that a change should be described properly but I don't see how this redundancy helps.

**Review by shuse2 — APPROVED** [review]

**Comment by willclarktech** [comment]
@webmaster128 For a small fix like this for an obvious problem with an obvious solution, considered on its own, it's obviously not so important to have an issue. But we have trouble sometimes with contributors submitting PRs involving work we either (a) have already started in-house, or (b) don't want to include. Discussing changes in an issue before anyone starts working on a PR helps avoid these situations. We place a lot of emphasis on consistency and uniformity, so we apply this approach to *all* PRs no matter how small.

**Comment by webmaster128** [comment]
Okay, thanks!

**Pull request merged**
